import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { Route, CheckCircle, Circle, Sparkles, Trophy, Loader2, Filter, List, LayoutGrid } from 'lucide-react'
import useRoadmapStore from '../store/useRoadmapStore'

const typeColors = {
  'problem-solving': 'badge-accent',
  'project': 'badge-info',
  'mock-interview': 'badge-warning',
  'video': 'badge-neutral',
  'article': 'badge-neutral',
  'quiz': 'badge-success',
  'resume': 'badge-danger',
  'behavioral': 'badge-warning',
  'system-design': 'badge-info',
}

export default function RoadmapPage() {
  const { roadmap, tasks, loading, error, generateRoadmap, fetchTasks, toggleTask } = useRoadmapStore()
  const [filter, setFilter] = useState('all')
  const [view, setView] = useState('list')

  useEffect(() => {
    fetchTasks()
    if (!roadmap && !error) generateRoadmap()
  }, [])

  const completedTasks = tasks.filter((t) => t.completed).length
  const progress = tasks.length > 0 ? Math.round((completedTasks / tasks.length) * 100) : 0

  const taskTypes = ['all', ...new Set(tasks.map(t => t.taskType || t.type).filter(Boolean))]
  const filteredTasks = filter === 'all' ? tasks : tasks.filter(t => (t.taskType || t.type) === filter)

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-zinc-100 tracking-tight">Your Roadmap</h1>
          <p className="text-sm text-zinc-500 mt-1">Personalized learning path generated by AI</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setView(view === 'list' ? 'grid' : 'list')}
            className="btn btn-secondary btn-sm btn-icon"
            title="Toggle view"
          >
            {view === 'list' ? <LayoutGrid className="w-4 h-4" /> : <List className="w-4 h-4" />}
          </button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-3">
        {[
          { label: 'Total Tasks', value: tasks.length, color: 'text-indigo-400' },
          { label: 'Completed', value: completedTasks, color: 'text-emerald-400' },
          { label: 'Progress', value: `${progress}%`, color: 'text-amber-400' },
        ].map(({ label, value, color }) => (
          <div key={label} className="card p-4">
            <p className="text-xs text-zinc-500 mb-1">{label}</p>
            <p className={`text-2xl font-bold ${color}`}>{value}</p>
          </div>
        ))}
      </div>

      {/* Progress bar */}
      {tasks.length > 0 && (
        <div className="card p-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs text-zinc-500">Overall Progress</span>
            <span className="text-xs font-semibold text-zinc-300">{progress}%</span>
          </div>
          <div className="w-full h-2 bg-zinc-800 rounded-full overflow-hidden">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${progress}%` }}
              transition={{ duration: 0.8, ease: 'easeOut' }}
              className="h-full bg-gradient-to-r from-indigo-500 to-violet-500 rounded-full"
            />
          </div>
        </div>
      )}

      {/* Filter */}
      {tasks.length > 0 && (
        <div className="flex items-center gap-2 overflow-x-auto pb-1">
          <Filter className="w-4 h-4 text-zinc-600 flex-shrink-0" />
          {taskTypes.map((type) => (
            <button
              key={type}
              onClick={() => setFilter(type)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-all ${
                filter === type
                  ? 'bg-indigo-500/12 text-indigo-400 border border-indigo-500/25'
                  : 'text-zinc-500 hover:text-zinc-300 border border-zinc-800 hover:border-zinc-700'
              }`}
            >
              {type === 'all' ? 'All' : type}
            </button>
          ))}
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="flex items-center justify-center py-20">
          <div className="flex flex-col items-center gap-3">
            <Loader2 className="w-8 h-8 text-indigo-400 animate-spin" />
            <p className="text-sm text-zinc-500">Generating your personalized roadmap...</p>
          </div>
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="card p-8 text-center">
          <Sparkles className="w-8 h-8 text-amber-400 mx-auto mb-3" />
          <p className="text-sm text-zinc-300 mb-1">Roadmap generation needs onboarding data</p>
          <p className="text-xs text-zinc-600">Please complete onboarding first</p>
        </div>
      )}

      {/* Empty */}
      {!loading && !error && tasks.length === 0 && (
        <div className="card p-10 text-center">
          <Route className="w-10 h-10 text-zinc-700 mx-auto mb-3" />
          <p className="text-sm text-zinc-500">No tasks yet. Try regenerating your roadmap.</p>
        </div>
      )}

      {/* Tasks */}
      {!loading && filteredTasks.length > 0 && (
        <div className={view === 'grid' ? 'grid sm:grid-cols-2 gap-3' : 'space-y-2'}>
          {filteredTasks.map((task, index) => (
            <motion.div
              key={task._id}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.02 }}
              className={`card p-4 transition-all ${
                task.completed ? 'border-emerald-500/15 opacity-70' : 'hover:border-zinc-700'
              }`}
            >
              <div className="flex items-start gap-3">
                <button
                  onClick={() => toggleTask(task._id, !task.completed)}
                  className="mt-0.5 flex-shrink-0"
                >
                  {task.completed ? (
                    <CheckCircle className="w-5 h-5 text-emerald-400" />
                  ) : (
                    <Circle className="w-5 h-5 text-zinc-700 hover:text-indigo-400 transition-colors" />
                  )}
                </button>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <h3 className={`text-sm font-medium ${task.completed ? 'text-zinc-600 line-through' : 'text-zinc-200'}`}>
                      {task.title}
                    </h3>
                    <span className={`badge text-[11px] ${typeColors[task.taskType || task.type] || 'badge-neutral'}`}>
                      {task.taskType || task.type}
                    </span>
                    {task.difficulty && (
                      <span className={`badge text-[11px] ${
                        task.difficulty === 'easy' ? 'badge-success' :
                        task.difficulty === 'medium' ? 'badge-warning' : 'badge-danger'
                      }`}>
                        {task.difficulty}
                      </span>
                    )}
                  </div>
                  {task.description && (
                    <p className="text-xs text-zinc-600 line-clamp-2">{task.description}</p>
                  )}
                  {task.platformLink && (
                    <a
                      href={task.platformLink}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-xs text-indigo-400 hover:text-indigo-300 mt-1 inline-block"
                    >
                      Open on {task.platform || 'Platform'} →
                    </a>
                  )}
                </div>
                <div className="flex items-center gap-1 text-xs text-amber-400/70 flex-shrink-0">
                  <Trophy className="w-3 h-3" />
                  +{task.points || 10}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  )
}
